---
# tasks file for test-roles/roles
- name: This script is to ping
  action: ping

- name: variable
  debug:
    msg: "{{ greeting }}"

- name: ensure httpd service is stopped
  service:
    name: httpd
    state: stopped

